version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '5001:5001'
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      PROFILE: development

  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend
