services:
  - type: web
    name: flask-backend
    env: docker
    rootDir: backend
    repo: https://github.com/ilaydadastan/adcash-campaign-management
    branch: main
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true
    envVars:
      - key: ACTIVE_PROFILE
        value: production

  - type: web
    name: react-frontend
    env: docker
    rootDir: frontend
    repo: https://github.com/ilaydadastan/adcash-campaign-management
    branch: main
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - frontend/**
    autoDeploy: true
    envVars:
      - key: VITE_REACT_APP_URL
        value: https://react-frontend-hl44.onrender.com
      - key: VITE_APP_API_URL
        value: https://flask-backend-cmeg.onrender.com/api