services:
  - type: web
    name: flask-backend
    env: docker
    rootDir: backend
    repo: https://github.com/ilaydadastan/adcash-campaign-management
    branch: main
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true

  - type: web
    name: react-frontend
    env: docker
    rootDir: frontend
    repo: https://github.com/ilaydadastan/adcash-campaign-management
    branch: main
    dockerfilePath: frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    autoDeploy: true